language: csharp
sudo: required
dotnet: 5.0.100
dist: xenial
before_install:
  - chmod +x build.sh
script:
  export FrameworkPathOverride=/usr/lib/mono/4.8-api/ && ./build.sh
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - FAKE_DETAILED_ERRORS=true